logger:
  level: ${LOG_LEVEL}
  env: ${ENV}
db:
  name: ${POSTGRES_DB}
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  ssl: "allow"
http:
  server:
rabbitmq:
  job_queue: "jobs"
  result_exchange: "results"
  statistics_exchange: "stats"
  host: ${RABBITMQ_HOST}
  port: ${RABBITMQ_PORT}
  user: ${RABBITMQ_DEFAULT_USER}
  password: ${RABBITMQ_DEFAULT_PASS}