logger:
  level: "debug"
  env: "local"
db:
  name: "postgres"
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  ssl: "allow"
http:
  server:
rabbitmq:
  host: "localhost"
  port: "15672"
  user: "guest"
  password: "guest"